print('Usandoa a funcao input para coletar dados do usuario')
name = input('Qual o seu naome? ')
idade =input('Digite a sua idade')
idade_coersao = int(idade) 
print(f'Seu nome e {name=}e a sua idade: {idade_coersao=}')